name: Pull Request Checker
on:
  pull_request:

jobs:
  syntax-check:
    name: Check syntax
    runs-on: ubuntu-latest
    container: python:3.11
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create virtual environment
        run: make venv
      - name: Syntax check
        run: make check

  build-error-check:
    name: Check build error
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create virtual environment
        run: make venv
      - name: Build documentation
        run: make
